[tools]
dotnet = "10.0.102"
opentofu = "1.11.3"
terragrunt = "0.97.2"
atlas = "1.0.0"

[vars]
DATABASE_URL = "postgresql://user:password@localhost:5432/milkround"
DATABASE_DEV_URL = "postgresql://user:password@localhost:5432/milkround_dev"

[tasks."api:build"]
description = "Build the API Service"
run = "dotnet build src/MilkRound.slnx"

[tasks.test]
description = "Run API Service Tests"
run = "dotnet test src/MilkRound.slnx--no-build"
depends = ["api:build"]

[tasks."api:run"]
description = "Run the API Service"
run = "dotnet run --project src/Api.Service/Api.Service.csproj --no-restore --no-build"
depends = ["api:build"]

[tasks."db:migrate"]
description = "Apply database schema migrations"
run = "atlas schema apply --to src/Schema --url $DATABASE_URL --dev-url $DATABASE_DEV_URL"