// Three visual directions for the Milkround customer app.
// Each theme defines tokens; components read them via props.

const themes = {
  farmhouse: {
    key: 'farmhouse',
    name: 'Farmhouse',
    blurb: 'Cream + sage, with butter, terracotta & sky accents.',
    font: "'Fraunces', 'Georgia', serif",
    fontBody: "'Nunito Sans', 'Inter', system-ui, sans-serif",
    bg: '#F7F1E3',
    card: '#FFFDF7',
    border: 'rgba(74, 92, 65, 0.14)',
    text: '#2C3A2A',
    textSoft: '#6B7A65',
    textMuted: '#9AA396',
    primary: '#4A7C59',
    primaryInk: '#FFFDF7',
    accent: '#C97B4A',
    chipBg: '#EFE6CF',
    chipActive: '#4A7C59',
    chipActiveInk: '#FFFDF7',
    focusRing: 'rgba(74,124,89,.35)',
    shadow: '0 1px 0 rgba(74,92,65,.04), 0 8px 24px rgba(74,92,65,.06)',
    radius: 18,
    radiusSmall: 12,
    statusBar: '#2C3A2A',
    headerAccent: "linear-gradient(180deg, #F7F1E3 0%, #FFFDF7 100%)",
    // Extended palette
    butter:     '#E9B949', // warm butter yellow
    butterSoft: '#F6E4B2',
    terracotta: '#C97B4A',
    terraSoft:  '#F1D7C4',
    sky:        '#6F9DB8', // a milk-morning blue
    skySoft:    '#D5E3EB',
    berry:      '#A84D5A', // rare pop
    cream:      '#FFF6E0',
    forest:     '#2E4B33', // deeper green for emphasis
    // Accent rotation for day badges / product tiles
    accentRotation: ['#4A7C59', '#E9B949', '#C97B4A', '#6F9DB8', '#A84D5A', '#2E4B33', '#7A8B5A'],
  },
  crisp: {
    key: 'crisp',
    name: 'Crisp',
    blurb: 'White, mono, minimal. Lots of air.',
    font: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    bg: '#FFFFFF',
    card: '#FFFFFF',
    border: '#EDEDED',
    text: '#111111',
    textSoft: '#555555',
    textMuted: '#9A9A9A',
    primary: '#111111',
    primaryInk: '#FFFFFF',
    accent: '#111111',
    chipBg: '#F4F4F4',
    chipActive: '#111111',
    chipActiveInk: '#FFFFFF',
    focusRing: 'rgba(17,17,17,.18)',
    shadow: 'none',
    radius: 10,
    radiusSmall: 6,
    statusBar: '#111111',
    headerAccent: '#FFFFFF',
  },
  editorial: {
    key: 'editorial',
    name: 'Editorial',
    blurb: 'Deep green + ivory. Quiet, considered.',
    font: "'Instrument Serif', 'Cormorant Garamond', Georgia, serif",
    fontBody: "'Inter', system-ui, sans-serif",
    bg: '#F3EFE4',
    card: '#FBF8EE',
    border: 'rgba(27, 52, 43, 0.14)',
    text: '#1B342B',
    textSoft: '#5B6C60',
    textMuted: '#90978E',
    primary: '#1B342B',
    primaryInk: '#FBF8EE',
    accent: '#B36A3A',
    chipBg: '#EBE5D3',
    chipActive: '#1B342B',
    chipActiveInk: '#FBF8EE',
    focusRing: 'rgba(27,52,43,.28)',
    shadow: '0 1px 0 rgba(27,52,43,.04), 0 12px 32px rgba(27,52,43,.08)',
    radius: 4,
    radiusSmall: 2,
    statusBar: '#1B342B',
    headerAccent: '#F3EFE4',
  },
};

window.themes = themes;
